// src/components/navigation/NavigationItem.tsx
import React from 'react';
import { Menu } from 'semantic-ui-react';
import { Link } from 'react-router-dom';

interface NavigationItemProps {
    text: string;
    href: string;
}

export const NavigationItem = (props: NavigationItemProps) => {
    const renderAnchorLink = () => {
        const handleClick = (
            event: React.MouseEvent<HTMLAnchorElement, MouseEvent>,
        ) => {
            const id = event.currentTarget.href.split('#')[1];
            const elem = document.getElementById(id);

            if (elem !== null) elem.scrollIntoView({ behavior: 'smooth' });
            event.preventDefault();
        };

        return (
            <a href={props.href} onClick={(e) => handleClick(e)}>
                <Menu.Item link>{props.text}</Menu.Item>
            </a>
        );
    };

    const renderRouterLink = () => {
        return (
            <Link to={props.href}>
                <Menu.Item link>{props.text}</Menu.Item>
            </Link>
        );
    };

    return (
        <div className='navigation-item'>
            {props.href.startsWith('#')
                ? renderAnchorLink()
                : renderRouterLink()}
        </div>
    );
};

// src/components/NavigationItem.vue
<template>
  <li class="navigation-item">
    <a :href="href" @click.prevent="onClick">
      <slot></slot>
    </a>
  </li>
</template>

<script lang="ts">
import { Vue, Prop, Component } from "vue-property-decorator";

@Component
export default class NaviagtionItem extends Vue {
  @Prop({ required: true }) readonly href!: string;

  private onClick({ currentTarget }: MouseEvent) {
    const id = (currentTarget as HTMLAnchorElement).href.split("#")[1];
    const elem = document.getElementById(id);

    if (elem !== null) elem.scrollIntoView({ behavior: "smooth" });
  }
}
</script>

<style lang="scss" scoped>
.navigation-item {
  &:not(:last-child) {
    @apply pr-6;
  }

  a {
    @apply text-sm;
    @apply text-white;

    @apply opacity-75;
    @apply transition-opacity;
    @apply duration-200;

    &:hover {
      @apply opacity-100;
    }
  }
}
</style>
